In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import gym
import numpy as np

In [4]:
env = gym.make('FrozenLake-v0')
# env = gym.make('')

[2017-04-25 22:09:51,729] Making new env: FrozenLake-v0


### Q-Learning

- Initialize $V(s)$ arbitrarily
- Repeat for each episode
- Initialize s
- Repeat (for each step of episode)
- -    $\alpha \leftarrow$ action given by $\pi$ for $s$
- - Take action a, observe reward r, and next state s'
- - $V(s) \leftarrow V(s) + \alpha [r = \gamma V(s') - V(s)]$ 
- - $s \leftarrow s'$
- until $s$ is terminal

In [5]:
#Initialize table with all zeros
Q = np.zeros([ env.observation_space.n, env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    # The Q-Table learning algorithm
    while j < 99:
        j+=1
        
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [6]:
print("Final Q-Table Values")
print(Q)

Final Q-Table Values
[[  9.68298520e-03   2.52440667e-01   7.81879647e-03   7.86970395e-03]
 [  1.01900279e-04   9.04180375e-04   1.12535716e-03   1.79578623e-01]
 [  2.10233738e-03   1.19169909e-03   7.15905370e-03   1.62634731e-01]
 [  4.12239206e-03   6.68492742e-04   1.55813606e-04   1.58555908e-01]
 [  4.04512425e-01   7.93969307e-05   1.41857740e-03   1.19017381e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.11203350e-02   1.18966870e-08   1.83770956e-04   5.43247263e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  5.22098143e-04   3.65619689e-04   1.85192169e-03   3.66415199e-01]
 [  0.00000000e+00   3.64745008e-01   7.40189803e-04   8.45182550e-04]
 [  3.62264518e-01   4.24739122e-05   3.97017112e-04   3.76978430e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.62011399e-03   3.26441758e-03   3.52504480e-01   2

In [7]:
print("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.3635


In [8]:
cd ..

/Users/miguel/Jottacloud/HedgingRL


In [9]:
import gym
import gym.envs
import numpy as np

In [10]:
import gym_bs

In [11]:
gym.spaces.Tuple?

In [62]:
gym.envs.register(id='bs-v3',
                  entry_point='gym_bs.envs:EuropeanOptionEnv',
                  kwargs={'t': 1000})

In [68]:
env = gym.make('bs-v3')

[2017-04-25 23:56:31,360] Making new env: bs-v3


In [39]:
env.observation_space.sample()
# env.action_space.contains(1)

(array([ 3.47383142]), array([ 0.4634587]), array([-27.04647813]))

In [16]:
env.observation_space.sample()

(array([ 5.92844618]), array([ 0.84426575]), array([ 71.58912352]))

In [69]:
# Q = np.zeros([ env.observation_space.n, env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    
    done = False
    while not done:
        a = env.action_space.sample()
        s1, r, done, _ = env.step(a)
    print("=======", r)

======= -120.977265595
======= -160.498531384
======= -53.0271484789
======= 3.22236683389
======= -58.2844256891
======= -132.09974643
======= -437.142074727
======= -273.327274155
======= -303.658789076
======= -310.12913542
======= -16.8074036825
======= -333.249979448
======= -10.4538202153
======= 315.990741559
======= 144.818518954
======= 456.635295364
======= 552.832405502
======= 615.195181781
======= 527.703877504
======= 857.881325998
======= 487.010047267
======= 308.891682195
======= 353.234475771
======= 337.672454889
======= 443.415324952
======= 293.471945332
======= 792.685186962
======= 883.909831518
======= 1000.38718453
======= 1057.64354371
======= 1190.85636133
======= 1182.69393754
======= 1230.50841039
======= 1265.77230103
======= 1013.33340699
======= 936.930810485
======= 1157.60835878
======= 1057.18106192
======= 837.053968464
======= 660.767907853
======= 679.356803718
======= 546.477873724
======= 864.519716578
======= 120.465453884
======= 146.711456276


======= -4757.4871383
======= -4745.16475281
======= -4738.28076088
======= -4758.1677789
======= -4645.27986453
======= -4490.68729076
======= -4705.59124047
======= -4588.20322353
======= -4574.02018041
======= -4598.74653237
======= -4637.88543034
======= -4271.33359302
======= -4897.28707766
======= -4877.22012319
======= -4808.84000833
======= -4862.81649326
======= -4880.77609903
======= -5028.68024096
======= -4960.54315144
======= -4987.2110856
======= -5058.85680105
======= -5209.60881888
======= -5303.43751941
======= -5601.68381318
======= -4700.78134835
======= -4548.00367477
======= -4741.24290936
======= -4901.76036685
======= -4952.81253345
======= -4869.97816492
======= -5098.66962752
======= -5165.60087485
======= -5357.9666966
======= -4984.45819641
======= -5326.68191954
======= -4179.53099277
======= -3878.56898919
======= -5289.59603804
======= -4540.25946268
======= -4548.63954089
======= -4070.03534851
======= -4794.8396029
======= -4769.79039513
======= -4749.78

======= -8921.7247454
======= -9002.81191702
======= -9022.4484311
======= -9024.89737102
======= -9080.77867519
======= -9228.6661427
======= -9292.13914112
======= -9313.45242858
======= -9273.00622609
======= -9060.87274188
======= -9076.59871298
======= -8809.33174999
======= -9188.3381412
======= -9211.02056551
======= -9223.66242426
======= -9041.62981688
======= -8918.71718918
======= -8970.92407048
======= -8966.23495061
======= -8693.37609848
======= -9031.28437082
======= -8812.83134336
======= -8835.62220304
======= -8680.08272524
======= -8598.06351445
======= -8662.68888849
======= -8712.16488606
======= -8741.76597079
======= -8583.37997601
======= -8574.90673123
======= -8384.00524857
======= -8840.52001434
======= -8773.71419736
======= -8710.32710735
======= -8748.52160511
======= -8630.03745711
======= -8471.9413562
======= -8659.12821803
======= -8991.692132
======= -8783.52556296
======= -8473.16415698
======= -8425.46215272
======= -8347.82079505
======= -8325.1251

======= -7986.01142545
======= -7957.88643554
======= -8080.73677413
======= -8198.02663201
======= -8247.07630913
======= -8197.86237047
======= -8181.45521319
======= -8376.543666
======= -8402.55979613
======= -8355.84687952
======= -8331.33920604
======= -8154.90242061
======= -8090.45898521
======= -8049.09154993
======= -7493.55883571
======= -8402.00421583
======= -8553.23732778
======= -9004.83853622
======= -8963.51878793
======= -8989.84393365
======= -8941.18864228
======= -8940.31484836
======= -9069.63199569
======= -9151.52261644
======= -9246.20423844
======= -9229.47556992
======= -9134.13549134
======= -9194.91744628
======= -8942.27139027
======= -9533.59956554
======= -9010.27515587
======= -9037.76513514
======= -8989.96655011
======= -8905.17847725
======= -9049.75893652
======= -8894.63026165
======= -8837.45461621
======= -9076.2101012
======= -8774.79705134
======= -8581.32278259
======= -7271.46430705
======= -8453.15267617
======= -8345.45635434
======= -8281.

======= -5818.64425694
======= -5791.53757988
======= -4902.61809708
======= -4901.32561644
======= -4930.74202509
======= -4948.94849734
======= -4912.35797345
======= -4652.80954282
======= -5131.26598358
======= -4767.79628177
======= -4503.81493425
======= -4522.80159605
======= -4809.20351607
======= -4237.04713677
======= -4100.07591707
======= -4109.49923924
======= -3966.19941917
======= -3881.98306769
======= -3981.04059584
======= -3987.1587098
======= -4054.94464147
======= -4271.3107194
======= -4286.78602999
======= -4462.79923419
======= -4414.7109221
======= -4617.81724019
======= -4489.55209834
======= -4886.20073681
======= -4908.00551895
======= -5033.94741221
======= -4983.76492563
======= -4848.37175491
======= -4692.91151152
======= -4619.65279167
======= -4821.19580002
======= -5008.79763126
======= -5380.16096266
======= -4584.71906883
======= -4262.84735034
======= -4968.60955469
======= -4996.08900339
======= -5049.36746592
======= -4826.85827016
======= -4797.

======= -6831.02703613
======= -7161.37064166
======= -7078.05831381
======= -7466.17809971
======= -7493.27960572
======= -7419.14942655
======= -7322.943401
======= -7212.36647463
======= -7182.7835799
======= -7280.08331021
======= -7617.19842654
======= -7354.07777396
======= -7392.92301949
======= -7524.94507671
======= -7431.78342532
======= -7532.68866453
======= -7501.32548409
======= -7323.78633572
======= -7571.09963659
======= -8382.92369534
======= -8573.54157825
======= -8543.74741239
======= -8461.8129237
======= -8716.86812952
======= -8548.99640823
======= -8613.97210375
======= -8560.46279713
======= -8304.70137573
======= -8189.45332171
======= -8180.11850206
======= -8293.61989715
======= -8562.42977622
======= -8211.4977784
======= -8145.76621272
======= -8004.82691971
======= -7866.48240627
======= -7460.78190659
======= -7461.45783511
======= -7395.14532262
======= -7380.31604346
======= -7280.55751652
======= -7648.00565646
======= -7731.20766785
======= -8373.47

In [46]:
s1

0

In [40]:
from blackscholes import blackScholes
blackScholes(0, 1, 1, 0.1)

{'delta': 0.5, 'gamma': 0, 'npv': 0.0, 'theta': 0, 'vega': 0.0}